# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BackendCaseStudies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Bolts' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # Pods for BackendCaseStudies

end
